fix: move at-rules to end of nested responsive states
gregberge/xstyled pull request #327
Opened 2021-11-16 16:42 UTC by agriffis

## Summary

Move at-rules to the end of sorted styles, so that nested states can override. Fixes #288 

## Alternative

This _almost_ works:

```diff
-   const variants = { ...medias, ...states }
+  const variants = { ...states, ...medias }
```

but it's not enough, because `states` can contain at-rules too. The xstyled-provided `states` already does, and the developer could also supply their own, for instance with `@supports`

so instead we explicitly move at-rules to the end, similar to the way that `sortStyles` works.

## Test plan

Added a new test with a custom Jest matcher to ensure that rules are emitted in order. Without the code change, it fails like this:

```
 FAIL  packages/system/src/style.test.ts
  #style
    #themeGetter
      ✓ reads from theme (2 ms)
      ✓ supports second arg default
      ✓ uses first as default without second arg
      ✓ uses "default" value in theme when `true`
      ✓ supports shorthand mode
      ✓ supports multiple mode (1 ms)
      ✓ supports both shorthand and multiple modes
      ✓ supports array (1 ms)
      ✓ supports transform func
      ✓ supports transform func from theme (1 ms)
    #style
      ✓ works without any theme (1 ms)
      ✕ works with variants (6 ms)
      ✓ works with breakpoints (1 ms)
      ✓ works with a theme
      ✓ works with theme functions
      ✓ allows apply
      mixins
        ✓ supports functions (1 ms)

  ● #style › #style › works with variants

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Array [
        "fontFamily: title",
    -   "&:hover { fontFamily: title2 }",
        "@media (min-width: 400px) { fontFamily: title3 }",
        "@media (min-width: 400px) { &:hover { fontFamily: title4 } }",
    +   "&:hover { fontFamily: title2 }",
      ]

      31 |   toEqualRules(a, b) {
      32 |     expect(a).toEqual(b)
    > 33 |     expect(paths(a).map(asRule)).toEqual(paths(b).map(asRule))
         |                                  ^
      34 |     return { pass: true, message: () => 'Key order expected to match.' }
      35 |   },
      36 | })
```

2021-11-17 01:58 UTC, agriffis commented
Instead of the custom matcher, I simplified the test to verify key order with JSON.stringify. Amended and force-pushed.

2021-11-18 20:23 UTC, gregberge reviewed
I am afraid it will kill perf. Could you please run benchmarks and try to optimize it?

2021-11-19 16:15 UTC, agriffis commented
@gregberge To be honest, there's hardly a perf impact. I benchmarked but it's not even measurable without heavily exaggerated inputs, because it's a single loop over a short list that modifies the object in place, and the result is cached by `getCachedVariants` anyway.

Still, for an alternative, see the latest commit which just warns in development mode. The trickiest part is that the developer needs to know to insert `defaultTheme.states` in the middle:

```js
theme = {
  ...defaultTheme,
  states: {
    foo: '&:foo',
    bar: '&:bar',
    ...defaultTheme.states,
    xyz: '@supports(xyz)',
  },
}
```

This isn't too bad but would need to be documented, and the warning should probably point to the documentation, otherwise it will be a frequent stumbling block. It also assumes they aren't _overriding_ existing states, which is trickier to get the order right.

I can see benefits both ways. The original approach is more automatic and therefore easier. The latter approach is more explicit but forces the developer to manage their own complexity. What do you think?

2022-04-15 07:10 UTC, gregberge requested changes
What you are asking to the user here is nearly impossible if it uses the base theme (with spread operator). We have to sort rules in xstyled. But efficiently, only once, then cache the result.

2022-04-15 13:42 UTC, agriffis commented
> What you are asking to the user here is nearly impossible if it uses the base theme (with spread operator).

Right, I don't think it's a good solution either. It was merely to give you an option since you expressed concern about the original approach.

> We have to sort rules in xstyled. But efficiently, only once, then cache the result.

That's how my original proposal worked because of `getCachedVariants`. I'll just back out the temporary commit and it sounds like we're on the same page?

2022-04-15 13:52 UTC, agriffis commented
@gregberge This should be all set now, lemme know if not.

2022-04-15 15:42 UTC, gregberge approved these changes

2022-04-15 15:42 UTC, merged