Update text.mdx
gregberge/xstyled pull request #374
Opened 2022-07-23 14:10 UTC by CurtisHumphrey

I think `text` is the key here not `fontSizes` as `fontSizes` in the `defaultTheme` is not an object like `text` is.

## Summary

Fixing an doc issue with the wrong key listed in the example.

## Test plan

none - changing only docs

2022-07-25 07:30 UTC, jguddas requested changes

2022-07-25 07:30 UTC, jguddas commented on website/pages/docs/typography/text.mdx
> +If you don't want to customize it, a set of `text` is already defined in default theme:
```suggestion
If you don't want to customize it, a set of `texts` is already defined in default theme:
```

2022-07-26 09:13 UTC, jguddas approved these changes

2022-08-11 11:35 UTC, RodrigoRVSN approved these changes

2022-10-05 13:24 UTC, merged

2022-10-05 13:24 UTC, gregberge commented
Thanks!